# Copy this to .github/workflows/release.yml in a monorepo that only needs GitHub Releases
# Requires in repo root:
#   - release-please-config.json
#   - .release-please-manifest.json

name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: studiocactus/meta/.github/workflows/release-please-monorepo.yml@main
    secrets: inherit
